- .gitignore
- projectAreas.js
1) Added a .gitignore to ignore the usual files/folders that don't require tracking.
2) Created a projectAreas.js file for the root directory that holds the JSON object containing the various potential project areas. This file may be moved later once scaffolding is up.
> added gitignore and projectAreas JSON file - move it later

- .gitignore
- README.md
- api/routes/api.route.js
- api/routes/apiRoute.js
- gulpfile.js
- package.json
- server.js
- src/index.html
- src/selfStarted/features/dashboard/dashboard.controller.js
- src/selfStarted/features/dashboard/dashboard.html
- src/selfStarted/features/dashboard/dashboard.module.js
- src/selfStarted/features/dashboard/dashboard.route.js
- src/selfStarted/features/landingPage/landingPage.controller.js
- src/selfStarted/features/landingPage/landingPage.html
- src/selfStarted/features/landingPage/landingPage.module.js
- src/selfStarted/features/landingPage/landingPage.route.js
- src/selfStarted/selfStarted.module.js
> Setup Done

- src/index.html
- src/selfStarted/features/landingPage/landingPage.html
- src/selfStarted/selfStarted.module.js
> added materializecss

- api/config/connection.config.js
- api/models/messages.model.js
- api/models/projects.model.js
- api/models/reviews.model.js
- api/models/users.model.js
Connection file completed for MongoDB, and models built out for: Users, Projects, Messages, and Reviews.
> Mongo models

- gulpfile.js
- package.json
- src/index.html
Also changed angular material to match our current version of angular 1.6
> added gulp-nodemon to package.json

- api/models/messages.model.js
- api/models/projects.model.js
- api/models/reviews.model.js
- api/models/users.model.js
Thought of a few issues while at dinner. :P Added in some trimming of fields where the data will be input by the user, and added in a field within the users collection to account for user's email address which is contained within the LinkedIn API response.
> More db work

- src/assets/css/main.style.css
- src/index.html
- src/selfStarted/features/components/createProjects/createProjects.html
error was an extra < inside the html, couldn't find it to remove but I did a work around
> injected the files,

- api/models/messages.model.js
- api/models/projects.model.js
- api/models/reviews.model.js
- api/models/users.model.js
- api/routes/api.route.js
Test data is being added, and retrieved. In postman:
Send a POST req to localhost:4000/api/testpost/ to add test user
Send a GET req to localhost:4000/api/testget/ to retrieve user data
> get and post test data working

- api/models/projects.model.js
- api/routes/api.route.js
Test project data routes working.
To add dummy project data, use Postman to route to:
Post method to localhost:4000/api/testprojectpost/
To read dummy project data, use Postman to route to:
Get method to localhost:4000/api/testprojectget/
> test project data and route working

- src/selfStarted/features/components/createProjects/createProjects.directive.js
- src/selfStarted/features/dashboard/dashboard.route.js
but form doesn't appear fullscreen
> fixed rendering problem

- gulpfile.js
- src/assets/css/main.style.css
- src/selfStarted/features/components/createProjects/createProjects.html
- src/selfStarted/features/dashboard/dashboard.html
- src/selfStarted/features/landingPage/landingPage.html
did some style changes to get form to expand still needs work
> added landing page finally got link working

- api/routes/api.route.js
- api/routes/projects.api.js
- api/routes/test.api.js
Separated the tests for dummy data into its own route file. Projects route is in its own file as.  We shall have a route file for each Model for all interactions for the model, this way its easier to find where  we need to change things and less chance of conflicts.
> cleaned up and split api files by routes

- api/models/projects.model.js
- api/models/users.model.js
- api/routes/projects.api.js
Includes the following changes:
1) Added lowercase versions of project name, and project location to projects model.
2) Added lowercase versions of first name, last name, and user location to users model.
3) Added lower case project name and project location to new project post route
4) Created a search projects get route that returns json of matching projects
> added backend stuff for projects and models

- api/routes/users.api.js
added a route for /users/searchusers for finding users/talent
> added searchUsers route

- api/routes/messages.api.js
- api/routes/reviews.api.js
Added get routes for messages and projects.
> Add more routes

- api/routes/api.route.js
Had forgotten to add the dependencies in the api.routes.js file to the users.api.js, reviews.api.js, and messages.api.js route files. Fixed that.
> added users messages and reviews routes dependencies to apiroute file

- api/models/projects.model.js
- api/routes/projects.api.js
- api/routes/users.api.js
Added isDeleted key to projects model to track whether user has deleted a project, added a /projects/updateProject route to allow user to either update or set isDeleted for the projects they own. Also fixed a missing semicolon in users.api.js file. Todo: make a route for user to get their own projects, and also update the searchprojects get route so only projects that are 'isDeleted : false' are returned.
> more routes added

- src/selfStarted/features/components/userProfile/userProfile.directive.js
- src/selfStarted/features/components/userProfile/userProfile.html
Modal is displaying user data.
> Modal Displays user info

- api/routes/users.api.js
Fixed the route for user updating their profile so that their program and college is also updated. The route is a post to /users/updateUser located in users.api.js
> updated users route

- api/routes/projects.api.js
only returning not deleted projects for full projects search route
> only returning not deleted projects for full projects search route

- api/routes/projects.api.js
> added route for user to get personal projects

- package.json
- server.js
removed favicon related npm package and code from package.json and server.js
> remove favicon npm related code

- api/routes/test.api.js
Updated post route to /api/testpost which posts a new dummy user to the database. After hitting this POST route, get the users _id from robomongo to then post test projects for that user using Postman and the /projects/newProject route. When adding projects for the dummy user, remember to build the key value pairings in the body of the request. To see which key value pairs are needed, check projects.api.js for the /projects/newProject POST route.
> updated testpost route to allow adding of dummy user account for testing

- src/selfStarted/features/projectsPage/projectsPage.controller.js
- src/selfStarted/features/projectsPage/projectsPage.html
Filter works by using the temporary delete button. Will change to a nicer button when I style pages Friday
> delete filter working

- src/selfStarted/features/components/findTalent/findTalent.directive.js
- src/selfStarted/features/components/findTalent/findTalent.html
Recruit button now properly gives back the correct id, and project name when pressed.  Still need to add the service call to flag the invite
> Recruit button is working as inteneded

- api/routes/projects.api.js
Added 3 routes for inviting talent, accepting the invite, and denying the invite.
> Three project routes

- src/selfStarted/features/projectsPage/projectsPage.html
Button added to Projects list user is being invited too.  Just visually there no logic in it yet.
> accept or deny invite button visually added

- api/routes/projects.api.js
removed default null for invited and assigned arrays for new projects
> removed null from default new project invited arrays

- src/assets/css/main.style.css
- src/selfStarted/features/components/createProjects/createProjects.html
- src/selfStarted/features/components/findTalent/findTalent.html
- src/selfStarted/features/components/searchProjects/searchProjects.html
- src/selfStarted/features/dashboard/dashboard.html
- src/selfStarted/features/dashboard/dashboard.route.js
ignore branch name stupid git didn't switch when I click on another branch.  Added some styling to the forms to make them more similar in design.
> added css to make forms similar in design

- api/routes/messages.api.js
- api/routes/projects.api.js
- api/routes/reviews.api.js
- api/routes/users.api.js
All four routing categories (reviews, messages, users, projects) updated routes to allow return of errors from back end when an error occurs, for front end parsing.
> Return errors

- src/selfStarted/features/components/searchProjects/searchProjects.html
Data within projects accordion put into a table with striped rows to add structured cleaner appearance.
> cleaned up projects data display

- src/selfStarted/features/projectsPage/projectsPage.html
Had forgotten to put in the UI improvement I had done, on the searchProjects component, also into the sidebar projects link. Fixed it so style is similar to searchProjects when displaying projects data content.
> more projectsUI

- src/assets/css/projects.style.css
- src/selfStarted/features/components/createProjects/createProjects.html
Added tooltips for the create a project page. Required adding tooltips bootstrap ui component to the createProjects.html file, and some custom class work to projects.style.css.
> added tooltips for project creation

- src/assets/css/findTalent.style.css
- src/assets/css/main.style.css
- src/assets/css/projects.style.css
Moved the css needed to get tooltips to work to the main style css file.
> moved tooltips css to main style file

- src/selfStarted/features/components/createProjects/createProjects.html
- src/selfStarted/features/components/findTalent/findTalent.html
- src/selfStarted/features/components/searchProjects/searchProjects.html
Added tooltips to all three top tab categories now. Pretty it up with CSS later. However, this completes the adding tool tips task.
> finished off tooltips

- README.md
Added the link to heroku deployed site to the readme
> added heroku link

- api/models/messages.model.js
- api/routes/messages.api.js
- api/routes/reviews.api.js
Updated messages collection model. Removed some messages routes that need to be re-done based on updated model.
> updated messages model

- api/models/messages.model.js
- api/models/projects.model.js
- api/routes/messages.api.js
- api/routes/projects.api.js
Filled out all routes relating to reading messages, posting messages, marking them read, or marking them deleted.
> updated projects and messages routes and models

- src/assets/css/messages.style.css
- src/selfStarted/features/components/services/messagesService/messages.service.js
- src/selfStarted/features/messagePage/messagesPage.controller.js
- src/selfStarted/features/messagePage/messagesPage.html
- src/selfStarted/features/messagePage/messagesPage.module.js
Messages for logged in user show up and can be read.
> messages populate panels

- api/routes/messages.api.js
Had to change findOneAndUpdate to findByIdAndUpdate for message read/delete functions.
> fixed message routing to id

- src/assets/css/messages.style.css
- src/selfStarted/features/components/services/messagesService/messages.service.js
- src/selfStarted/features/messagePage/messagesPage.controller.js
- src/selfStarted/features/messagePage/messagesPage.html
When a message is new. a new Message icon is displayed.  When user clicks a message the message should now get flagged as true and the icons disappear appropriately.
> new messages icon working in INBOX

- src/selfStarted/features/components/directives/findTalent/findTalent.directive.js
- src/selfStarted/features/components/directives/findTalent/findTalent.html
- src/selfStarted/features/components/directives/userProfile/userProfile.directive.js
modal for users pops up and needs to be changed into a direct messaging system instead
> modal for users

- src/selfStarted/features/components/directives/findTalent/findTalent.directive.js
- src/selfStarted/features/components/directives/userProfile/userProfile.directive.js
- src/selfStarted/features/components/directives/userProfile/userProfile.html
modal now only sends on submit, also fixed user image size to be more manageable
> messages only posting on submit now

- src/assets/css/findTalent.style.css
- src/selfStarted/features/components/directives/findTalent/findTalent.directive.js
- src/selfStarted/features/components/directives/userProfile/userProfile.directive.js
- src/selfStarted/features/components/directives/userProfile/userProfile.html
removed cancel button and added a X button to close in the corner instead
> fixed cancel message posting

- src/selfStarted/features/components/services/messagesService/messages.service.js
Final fix for messages for now
> messages only show ones sent to you

- src/selfStarted/features/profilePage/profilePage.controller.js
- src/selfStarted/features/profilePage/profilePage.html
They don't updated live like my previous changes due to no binding but they do update upon refresh
> new profile changes updated

- src/selfStarted/features/landingPage/landingPage.html
Tried to fix background image on landing page.
> landing page background css

- src/assets/css/main.style.css
- src/assets/css/messages.style.css
- src/assets/css/profile.style.css
- src/assets/css/projects.style.css
- src/selfStarted/features/messagePage/messagesPage.html
- src/selfStarted/features/profilePage/profilePage.html
- src/selfStarted/features/projectsPage/projectsPage.html
Changes some backgrounds and stuff.
> added some css all around
